<a href="https://colab.research.google.com/github/WisnuMukti11/KecerdasanBuatan/blob/main/Quiz_Free_UAS_Kecerdasan_Buatan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import math 
import random

class Algoritma_genetika :
	jum_chrom = 6 
	gen = ["a", "b", "c", "d"] 
	nilai_per_gen = {
		'min' : 0,
		'max' : 10
	} 
    
	crossover_rate = 50/100 #persen
	mutasi_rate = 10/100 #persen
	total_gen = 24

	next_gen = np.arange(4)
	stop = False

	def __init__(self):
		self.first_chrom = np.random.randint(low=self.nilai_per_gen['min'], high=self.nilai_per_gen['max'], size=(self.jum_chrom, len(self.gen)))
		print("******************************************inisialisasi*********************************************")
		print(self.first_chrom)
		print("***************************************************************************************************")

	def evaluasi_chrom(self, chrom, generasi):
		print("GENERASI ["+str(generasi)+"] *********")
		
		jum_chromo = len(chrom)
		o = np.arange(jum_chromo)   
		fitness = np.arange(jum_chromo, dtype='f')
		
		for x in range(len(chrom)):
		
			
			fo = abs((chrom[x][0]+2*chrom[x][1]+3*chrom[x][2]+4*chrom[x][3])-30)
			o[x] = fo
			

			fitn = 1/(fo+1)
			
			fitness[x] = fitn
			if(fitn == 1):
				self.stop = True
			print("CHROMOSOME {0} : {1}, fitness = {2}".format(x, np.array2string(chrom[x], separator=','), fitn))
		print("FITNESS SELESAI!!")
		print(o)
		
        

		Probab = np.arange(jum_chromo, dtype='f')
		
		total_fitness = fitness.sum() 
		Probab = fitness / total_fitness 
		print("Total fitness : {}".format(str(total_fitness)))
		print("Rata-rata fitness : {}".format(str(np.average(fitness))))
		print("Probabilitas : {}".format(np.array2string(Probab, separator=',')))
		print("Probabilitas Paling Tinggi : {}, Pada chromosome ke {}".format(Probab[Probab.argmax()], str(Probab.argmax())))
		print("CHROMOSOME YANG MUNGKIN TERPILIH : {}".format(np.array2string(chrom[Probab.argmax()], separator=',')))
		print("")
		print("")
		self.next_gen = chrom[Probab.argmax()]


		C = np.arange(jum_chromo, dtype='f')
		total_x = 0
		for x in range(len(Probab)):
			total_x += Probab[x]
			C[x] = total_x


		R = np.random.sample(len(fitness))
		chrom_baru = np.arange(jum_chromo*len(self.gen)).reshape(jum_chromo, len(self.gen))



		for y in range(len(R)):
			for k in range(len(chrom_baru)):
				if(R[y] < C[0]):
					chrom_baru[y] = chrom[0]
				elif((C[k-1] < R[y]) & (R[y] < C[k])):
					chrom_baru[y] = chrom[k]


		R = np.random.sample(jum_chromo)
		index_chrom_parent = [] # [1,2,3, ...]
		for p in range(len(R)):
			if(R[p] < self.crossover_rate):
				index_chrom_parent.append(p)
                

		posisi_cros = np.random.randint(low=1, high=len(self.gen), size=len(index_chrom_parent))


		offspring = np.arange(len(self.gen)*len(index_chrom_parent)).reshape(len(index_chrom_parent), len(self.gen))
		for i_parent in range(len(index_chrom_parent)):
			index_chrome_1 = index_chrom_parent[i_parent]
			if(i_parent == len(index_chrom_parent)-1):
				index_chrome_2 = index_chrom_parent[0]
			else:
				index_chrome_2 = index_chrom_parent[i_parent+1]
			cut_point = posisi_cros[i_parent]
			for p in range(len(chrom_baru[index_chrome_1])):
				if(p >= posisi_cros[i_parent]):
					offspring[i_parent][p] = chrom_baru[index_chrome_2][p]
				else:
					offspring[i_parent][p] = chrom_baru[index_chrome_1][p]

		for x in range(len(offspring)):
			chrom_baru[index_chrom_parent[x]] = offspring[x]
            

		total_gen = len(chrom) * len(chrom[0])
		jum_mutasi = self.mutasi_rate * total_gen 
		jum_mutasi = int(jum_mutasi)

		random_i_mutasi = np.random.randint(low=0, high=total_gen, size=jum_mutasi)

		for x in range(len(random_i_mutasi)):
			index_mutasi = random_i_mutasi[x]
			byk_kromosom = len(chrom)
			byk_gen = len(chrom[0])
			random_value = random.randint(self.nilai_per_gen['min'], self.nilai_per_gen['max'])
			if(index_mutasi <= byk_gen):
				chrom_baru[0][index_mutasi-1]
			else:
				posisi_y = index_mutasi/byk_gen
				posisi_y = int(posisi_y)
				posisi_x = index_mutasi % byk_gen
				chrom_baru[posisi_y][posisi_x] = random_value
		return chrom_baru

	def do_now(self):
		chromosome_current = self.first_chrom
		for generasi in range(0, self.total_gen):
			if(self.stop != True):
				chromosome_current = self.evaluasi_chrom(chromosome_current, generasi)
		print("*****************************************************************")
		print("All Done!")
		print("Chromosome Tertinggi dan Terbaik Adalah")
		print(self.next_gen)

run = Algoritma_genetika()
run.do_now()


******************************************inisialisasi*********************************************
[[1 3 8 5]
 [6 8 7 5]
 [5 3 7 5]
 [0 9 8 2]
 [3 8 5 0]
 [4 1 2 5]]
***************************************************************************************************
GENERASI [0] *********
CHROMOSOME 0 : [1,3,8,5], fitness = 0.045454545454545456
CHROMOSOME 1 : [6,8,7,5], fitness = 0.029411764705882353
CHROMOSOME 2 : [5,3,7,5], fitness = 0.043478260869565216
CHROMOSOME 3 : [0,9,8,2], fitness = 0.047619047619047616
CHROMOSOME 4 : [3,8,5,0], fitness = 0.2
CHROMOSOME 5 : [4,1,2,5], fitness = 0.3333333333333333
FITNESS SELESAI!!
[21 33 22 20  4  2]
Total fitness : 0.69929695
Rata-rata fitness : 0.11654949
Probabilitas : [0.06500035,0.04205905,0.06217425,0.0680956 ,0.28600153,0.47666922]
Probabilitas Paling Tinggi : 0.47666922211647034, Pada chromosome ke 5
CHROMOSOME YANG MUNGKIN TERPILIH : [4,1,2,5]


GENERASI [1] *********
CHROMOSOME 0 : [4,1,2,5], fitness = 0.3333333333333333
CHROMOSOME 1